### ISSUE TITLE
rfdiffusion/inference/../../models/Base_ckpt.pt not found

### ISSUE THREAD

**Issue by rmitch88** [RosettaCommons/RFdiffusion#162]
I am trying to run the unconditional monomer example code included in the readme. I copy and pasted the code from the readme and this is the message I got:

> Reading models from /home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/infer                                                                                                                                                             ence/../../models
[2023-11-29 18:20:15,343][rfdiffusion.inference.model_runners][INFO] - Reading c                                                                                                                                                             heckpoint from /home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/                                                                                                                                                             ../../models/Base_ckpt.pt
This is inf_conf.ckpt_path
/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/../../models/Ba                                                                                                                                                             se_ckpt.pt
Error executing job with overrides: ['contigmap.contigs=[150-150]', 'inference.o                                                                                                                                                             utput_prefix=test_outputs/test', 'inference.num_designs=10']
Traceback (most recent call last):
  File "/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/./scripts/run_inference.py",                                                                                                                                                              line 45, in main
    sampler = iu.sampler_selector(conf)
  File "/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/utils.p                                                                                                                                                             y", line 521, in sampler_selector
    sampler = model_runners.SelfConditioning(conf)
  File "/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/model_r                                                                                                                                                             unners.py", line 37, in __init__
    self.initialize(conf)
  File "/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/model_r                                                                                                                                                             unners.py", line 103, in initialize
    self.load_checkpoint()
  File "/home/ubuntu/RFdiffusion/RFdiffusion-1.1.0/rfdiffusion/inference/model_r                                                                                                                                                             unners.py", line 181, in load_checkpoint
    self.ckpt  = torch.load(
  File "/home/ubuntu/colabfold/localcolabfold/colabfold-conda/lib/python3.10/sit                                                                                                                                                             e-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/colabfold/localcolabfold/colabfold-conda/lib/python3.10/sit                                                                                                                                                             e-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/colabfold/localcolabfold/colabfold-conda/lib/python3.10/sit                                                                                                                                                             e-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/RFdiffusio                                                                                                                                                             n/RFdiffusion-1.1.0/rfdiffusion/inference/../../models/Base_ckpt.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Any ideas as to what is going wrong?

**Comment by roccomoretti** [comment]
There's a separate download step for the models which either might not have been performed, or may have failed for you. See the `wget` steps at https://github.com/RosettaCommons/RFdiffusion#getting-started--installation

**Comment by rmitch88** [comment]
Thank you that solved it
