### ISSUE TITLE
Not working with CUDA 11.1

### ISSUE THREAD

**Issue by crazyNi** [RosettaCommons/RFdiffusion#183]
I installed CUDA 11.1 but doesn't work. Does any one know why...
The python version is 3.9.18
CUDA version is 11.1
Pytorch version i tried both 1.9.1 and 2.1.2.

When i tried the design_unconditional.sh, i got the following errors:
(SE3nv) xtni@T640:~/tools/RFdiffusion/examples$ ./design_unconditional.sh
Traceback (most recent call last):
  File "/home/xtni/tools/RFdiffusion/examples/../scripts/run_inference.py", line 25, in <module>
    from rfdiffusion.inference import utils as iu
  File "/home/xtni/tools/RFdiffusion/rfdiffusion/inference/utils.py", line 6, in <module>
    from rfdiffusion.diffusion import get_beta_schedule
  File "/home/xtni/tools/RFdiffusion/rfdiffusion/diffusion.py", line 12, in <module>
    from rfdiffusion.util_module import ComputeAllAtomCoords
  File "/home/xtni/tools/RFdiffusion/rfdiffusion/util_module.py", line 7, in <module>
    import dgl
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from .backend import load_backend, backend_name
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/backend/__init__.py", line 109, in <module>
    load_backend(get_preferred_backend())
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/backend/__init__.py", line 43, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/_ffi/base.py", line 45, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/opt/miniconda3/envs/SE3nv/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/miniconda3/envs/SE3nv/lib/python3.9/site-packages/dgl/../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11

Here is my conda environment:
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename /opt/miniconda3/envs/SE3nv/conda-meta/decorator-5.1.1-pyhd3eb1b0_0.json.  Please remove this file manually (you may need to reboot to free file handles)
# packages in environment at /opt/miniconda3/envs/SE3nv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
backcall                  0.2.0              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
brotli-python             1.0.9            py39h6a678d5_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2023.12.12           h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2023.11.17       py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.16.0           py39h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
click                     8.1.7                    pypi_0    pypi
comm                      0.1.2            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
configparser              6.0.0                    pypi_0    pypi
cryptography              41.0.7           py39hdda0065_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               11.1.1              hb139c0e_12    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
debugpy                   1.6.7            py39h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
decorator                 5.1.0                    pypi_0    pypi
dgl-cuda11.1              0.9.1post1               py39_0    dglteam
dllogger                  1.0.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
e3nn                      0.3.3                    pypi_0    pypi
exceptiongroup            1.0.4            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
executing                 0.8.3              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freetype                  2.12.1               h4a9f257_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
future                    0.18.3           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
giflib                    5.2.1                h5eee18b_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.4              py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
importlib-metadata        6.0.0            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
importlib_metadata        6.0.0                hd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipykernel                 6.25.0           py39h2f386ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipython                   8.15.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jedi                      0.18.1           py39h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jpeg                      9e                   h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupyter_client            8.6.0            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupyter_core              5.5.0            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lcms2                     2.12                 h3be6417_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lerc                      3.0                  h295c915_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libblas                   3.9.0            12_linux64_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.17                 h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 13.2.0               h807b86a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran-ng            11.2.0               h00389a5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran5              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   13.2.0               h807b86a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.39               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.18.3               h6239696_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsodium                 1.0.18               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              13.2.0               h7e041cc_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.5.1                h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp                   1.3.2                h11a3e52_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp-base              1.3.2                h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libzlib                   1.2.13               hd590300_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lz4-c                     1.9.4                h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib-inline         0.1.6            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py39h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.1            py39hd3c417c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py39h51133e4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nest-asyncio              1.5.6            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  3.1              py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja                     1.10.2               h06a4308_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja-base                1.10.2               hd09550d_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.24.3           py39h14f4228_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.24.3           py39h31eccc5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
omegaconf                 2.3.0                    pypi_0    pypi
openjpeg                  2.4.0                h3ad879b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   3.0.12               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opt-einsum                3.3.0                    pypi_0    pypi
opt-einsum-fx             0.1.4                    pypi_0    pypi
packaging                 23.1             py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
parso                     0.8.3              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pickleshare               0.7.5           pyhd3eb1b0_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    10.0.1           py39ha6cbd5a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       23.3.1           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
platformdirs              3.10.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pooch                     1.7.0            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.36           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
protobuf                  4.25.1                   pypi_0    pypi
psutil                    5.9.0            py39h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ptyprocess                0.7.0              pyhd3eb1b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pure_eval                 0.2.2              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycparser                 2.21               pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pygments                  2.15.1           py39h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pynvml                    11.0.0                   pypi_0    pypi
pyopenssl                 23.2.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyrsistent                0.20.0                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.9.18               h955ad1f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python_abi                3.9                      2_cp39    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.9.1           cpu_py39hc5866cc_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.0           py39h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.31.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
rfdiffusion               1.1.0                     dev_0    <develop>
scipy                     1.10.1           py39h14f4228_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sentry-sdk                1.39.1                   pypi_0    pypi
setuptools                68.2.2           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
shortuuid                 1.0.11                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sleef                     3.5.1                h9b69904_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stack_data                0.2.0              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
subprocess32              3.5.4                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torchaudio                0.9.1                      py39    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
torchvision               0.15.2          cpu_py39h83e0c9b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tornado                   6.3.3            py39h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.65.0           py39hb070fc8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
traitlets                 5.7.1            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
typing_extensions         4.7.1            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tzdata                    2023c                h04d1e81_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.18          py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wandb                     0.12.0                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.41.2           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.4.5                h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zeromq                    4.3.4                h2531618_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.11.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.13               hd590300_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zstd                      1.5.5                hc292b87_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by johnnytam100** [comment]
same issue

```
(SE3nv) jupyter@tam-notebook-a10040gb-2:~/test/test_RFDiffusion_repeat-old_copy/RFdiffusion$ ./scripts/run_inference.py inference.output_prefix=example_outputs/design_ppi inference.input_pdb=input_pdbs/insulin_target.pdb 'contigmap.contigs=[A1-150/0 70-100]' 'ppi.hotspot_res=[A59,A83,A91]' inference.num_designs=10 denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0
Traceback (most recent call last):
  File "/home/jupyter/test/test_RFDiffusion_repeat-old_copy/RFdiffusion/./scripts/run_inference.py", line 25, in <module>
    from rfdiffusion.inference import utils as iu
  File "/home/jupyter/test/test_RFDiffusion_repeat-old_copy/RFdiffusion/rfdiffusion/inference/utils.py", line 6, in <module>
    from rfdiffusion.diffusion import get_beta_schedule
  File "/home/jupyter/test/test_RFDiffusion_repeat-old_copy/RFdiffusion/rfdiffusion/diffusion.py", line 12, in <module>
    from rfdiffusion.util_module import ComputeAllAtomCoords
  File "/home/jupyter/test/test_RFDiffusion_repeat-old_copy/RFdiffusion/rfdiffusion/util_module.py", line 7, in <module>
    import dgl
  File "/opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from .backend import load_backend, backend_name
  File "/opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/backend/__init__.py", line 109, in <module>
    load_backend(get_preferred_backend())
  File "/opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/backend/__init__.py", line 43, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/_ffi/base.py", line 45, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/opt/conda/envs/SE3nv/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/envs/SE3nv/lib/python3.9/site-packages/dgl/../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11
```

**Comment by crazyNi** [comment]
Try docker. That's easier.


Johnny Tam ***@***.***>于2024年1月9日 周二14:48写道：

**Comment by matteoferla** [comment]
Just to clarify (by obfuscatingly talking about Cuda 😵‍💫). TL;DR: copy code if below.

The conda env yaml installs Cuda toolkit 11.1 and this `undefined symbol` Cuda toolkit error was fixed in later versions, hence why the docker may work. Specifically: The docker installs 11.6. The PyTorch and DGL versions differ too:

* Cuda Toolkit 11.1 => 11.6†
* pytorch=1.9 => 1.12‡
* dgl-cuda11.1 which is 0.9 => 2.0

† The conda yaml install pytorch the old way, via conda, which has the unhyphenated anacondan `cudatoolkit` in its requirements (cf. [page](https://anaconda.org/pytorch/pytorch/files?page=9)) —the Nvidia channel modern one is the hyphenated `cuda-toolkit`, which may install less depending on the version.

‡About the PyTorch, 1.12 changes slightly some API endpoints IIRC, but the annoying `device` argument business happened in 2.0. So I reckon it's safe. The Dockerfile installs PyTorch the modern way via pip, which for newer version adds cuda toolkit within its triton package (which is reliable: the troublesome one is jaxlib's). However the image used is `nvcr.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04`, which might mean that that version of PyTorch does not install Cuda. For me, `find $CONDA_PREFIX -name "libdevice.*"` gave nothing after:

```bash
# common fluff
unset LD_LIBRARY_PATH
unset CUDA_HOME
unset CUDA_DIR
unset XLA_FLAGS

# install
export CONDA_PREFIX
conda create --name RFdiffusion -y python=3.9
conda activate RFdiffusion

# common fluff:
conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$CONDA_PREFIX:/.singularity.d/libs
conda env config vars set PYTHONUSERBASE=$CONDA_PREFIX
conda deactivate
conda activate RFdiffusion

# install
pip install -q --no-cache-dir \
                      dgl==1.0.2+cu116 -f https://data.dgl.ai/wheels/cu116/repo.html \
                      torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 \
                      e3nn==0.3.3 \
                      wandb==0.12.0 \
                      pynvml==11.0.0 \
                      git+https://github.com/NVIDIA/dllogger#egg=dllogger \
                      decorator==5.1.0 \
                      hydra-core==1.3.2 \
                      pyrsistent==0.19.3

REPO_ROOT=$HOME/👾👾/👾👾 pip install -q --no-cache-dir  $REPO_ROOT/env/SE3Transformer
REPO_ROOT=$HOME/👾👾/👾👾 pip install -q --no-cache-dir $REPO_ROOT --no-deps
```
So I run:
```bash
export CONDA_OVERRIDE_CUDA="11.6.2";
#export CONDA_ALWAYS_YES=yes;
conda install -y nvidia/label/cuda-11.6.2::cuda-toolkit
conda install -y nvidia/label/cuda-11.6.2::cuda-tools
conda install -y nvidia/label/cuda-11.6.2::cuda-nvrtc
conda install -y nvidia/label/cuda-11.6.2::libcufile
conda install -y nvidia/label/cuda-11.6.2::libcusparse
conda install -y nvidia/label/cuda-11.6.2::cuda-cudart
conda install -y nvidia/label/cuda-11.6.2::cuda-cudart-dev
```
The first install probably contains all the latter, but I don't want to assume and I had the snippet for 11.4 anyway.

Torch works fine:
```python
def test_torch():
    import torch
    assert torch.cuda.is_available(), 'Torch no CUDA available'
    print(torch.cuda.device_count(), torch.cuda.get_device_name(0)), 'Torch no CUDA devices counted'
    print(f'Using CuDNN: {torch.backends.cudnn.enabled} ({torch.backends.cudnn.m.version()})')
    device = torch.device("cuda")
    # Create a random tensor and transfer it to the GPU
    x = torch.rand(5, 3).to(device)
    print("A random tensor:", x)
    y = x * x
    print("After calculation:", y)
    print("Calculated on:", y.device)
    
test_torch()
```
As do the scripts.

**Comment by phongnq94** [comment]
So how to solve this problem?
