### ISSUE TITLE
IndexError: list index out of range  Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### ISSUE THREAD

**Issue by Hanoriega** [RosettaCommons/RFdiffusion#188]
Hello,

I am trying to do the fold conditioning example. I was able to trouble shoot the first example with the adj and ss pt files. But it mentions (although not necessary) you should also generate these files and then gives a script:

./scripts/run_inference.py inference.output_prefix=./scaffold_conditioned_test/test scaffoldguided.scaffoldguided=True scaffoldguided.target_pdb=False scaffoldguided.scaffold_dir=./examples/ppi_scaffolds_subset

I made the necessary changes for Windows:
python .\scripts\run_inference.py inference.output_prefix=.\scaffold_conditioned_test\test scaffoldguided.scaffoldguided=True scaffoldguided.target_pdb=False scaffoldguided.scaffold_dir=.\examples\ppi_scaffolds_subset

BUT it keeps giving me this indexerror?

Error executing job with overrides: ['inference.output_prefix=.\\scaffold_conditioned_test\\test', 'scaffoldguided.scaffoldguided=True', 'scaffoldguided.target_pdb=False', 'scaffoldguided.scaffold_dir=.\\examples\\ppi_scaffolds_subset']
Traceback (most recent call last):
  File "C:\User\mydir\RFdiffusion\scripts\run_inference.py", line 84, in main
    x_init, seq_init = sampler.sample_init()
  File "c:\users\mydir\rfdiffusion\rfdiffusion\inference\model_runners.py", line 776, in sample_init
    self.L, self.ss, self.adj = self.blockadjacency.get_scaffold()
  File "c:\users\mydir\rfdiffusion\rfdiffusion\inference\utils.py", line 891, in get_scaffold
    item = random.choice(self.scaffold_list)
  File "C:\Users\mydir\.conda\envs\SE3nv\lib\random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I am relatively new to coding, can someone help me to correct? Should I add something to the utils.py or random.py?

thanks,
Heather

**Comment by Hanoriega** [comment]
bumping as I still need help?

**Comment by roccomoretti** [comment]
I beleive the adj and ss pt files are created by the `make_secstruc_adj.py` helper script, not the `run_inference.py` script. See the top of the [Fold Conditioning section](https://github.com/RosettaCommons/RFdiffusion?tab=readme-ov-file#fold-conditioning) of the README for more.
