### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by KoningCheems** [RosettaCommons/RFdiffusion#197]
I am trying to run the ppi example with insulin.pdb on a docker container and running into this issue. Any ideas what this is? 

```
/usr/local/lib/python3.9/dist-packages/e3nn/o3/_spherical_harmonics.py:82: UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
To report the issue, try enable logging via setting the envvariable ` export PYTORCH_JIT_LOG_LEVEL=manager.cpp`
 (Triggered internally at  ../torch/csrc/jit/codegen/cuda/manager.cpp:237.)
  sh = _spherical_harmonics(self._lmax, x[..., 0], x[..., 1], x[..., 2])
Error executing job with overrides: ['inference.output_prefix=outputs', 'inference.input_pdb=inputs/insulin_target.pdb', 'contigmap.contigs=[A1-150/0 70-100]', 'ppi.hotspot_res=[A59,A83,A91]', 'inference.num_designs=1', 'inference.model_directory_path=./models', 'inference.schedule_directory_path=./schedule', 'denoiser.noise_scale_ca=0', 'denoiser.noise_scale_frame=0']
Traceback (most recent call last):
  File "/app/RFdiffusion/scripts/run_inference.py", line 122, in main
    os.makedirs(os.path.dirname(out_prefix), exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

```

My command: 

```
#!/bin/bash
mkdir inputs outputs models my_hydra
export HOME=$PWD


mv insulin_target.pdb ./inputs
bash /app/RFdiffusion/scripts/download_models.sh ./models

python3.9 /app/RFdiffusion/scripts/run_inference.py \
	inference.output_prefix=outputs \
	inference.input_pdb=inputs/insulin_target.pdb \
	'contigmap.contigs=[A1-150/0 70-100]' \
	'ppi.hotspot_res=[A59,A83,A91]' \
	inference.num_designs=1 \
	inference.model_directory_path=./models \
        inference.schedule_directory_path=./schedule \
	denoiser.noise_scale_ca=0 \
	denoiser.noise_scale_frame=0

```

**Comment by KoningCheems** [comment]
Never mind I found the solution 

Yes, you are correct. The inference.output_prefix parameter in the RFdiffusion software specifies both the output directory and the prefix for the output files.

When you run the script with inference.output_prefix=outputs/my_output, it will create the outputs directory if it doesn't exist, and then it will generate output files in this directory with names like my_output_1.pdb, my_output_2.pdb, etc., depending on the number of designs you specified
