### ISSUE TITLE
Is there a way to combine Inpainting and Fold Conditioning?

### ISSUE THREAD

**Issue by melinda589** [RosettaCommons/RFdiffusion#213]
Hello! Thank you for all the work and advancements into RFdiffusion!

I am interested in specifying the secondary structure of a new inpainted section of an input pdb. Essentially, I want to keep parts of the input pdb fixed, add connections between the fixed parts, and be able to specify those connections to be beta sheets or alpha helices or etc. 

I did try a few runs with provided _ss.pt and _adj.pt files to correspond to the secondary structure I would like the inpainted section to have, but I would get an Assertion Error:

Error executing job with overrides: ['inference.output_prefix=./outputs/guide_test', 'inference.input_pdb=inputs/1sp1_KT_relaxed1.pdb', 'contigmap.contigs=[A1-7/2-2/A8-30]', 'inference.num_designs=2', 'scaffoldguided.scaffoldguided=True', 'scaffoldguided.target_pdb=False', 'scaffoldguided.scaffold_dir=../helper_scripts/E2/']
Traceback (most recent call last):
  File "/scratch/ml1628/Klab/RFdiffusion/Zn_hinge/../scripts/run_inference.py", line 84, in main
    x_init, seq_init = sampler.sample_init()
  File "/cache/home/ml1628/RFdiffusion/rfdiffusion/inference/model_runners.py", line 851, in sample_init
    assert L_mapped==self.adj.shape[0]
AssertionError

Before I go down the rabbit hole of trying to get this to work, I wanted to ask: is this possible? Any and all advice would be greatly appreciated!

**Comment by thomas-tugwell** [comment]
@melinda589 Did you get this to work?

**Comment by RodenLuo** [comment]
Also wondering if this is possible and how to get it to work.
