### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory 

### ISSUE THREAD

**Issue by walee-1** [RosettaCommons/RFdiffusion#231]
When I try running the program, I get the error: 

/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/util.py:253: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:63.)
  Z = torch.cross(Xn, Yn)
[2024-04-24 19:37:12,033][__main__][INFO] - Found GPU with device_name NVIDIA GeForce GTX 1080 Ti. Will run RFdiffusion on NVIDIA GeForce GTX 1080 Ti
Reading models from /nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/../../models
[2024-04-24 19:37:12,034][rfdiffusion.inference.model_runners][INFO] - Reading checkpoint from /nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/../../models/Base_ckpt.pt
This is inf_conf.ckpt_path
/nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/../../models/Base_ckpt.pt
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/scripts-3.11/run_inference.py", line 194, in <module>
    main()
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/scripts-3.11/run_inference.py", line 54, in main
    sampler = iu.sampler_selector(conf)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/utils.py", line 511, in sampler_selector
    sampler = model_runners.SelfConditioning(conf)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/model_runners.py", line 37, in __init__
    self.initialize(conf)
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/model_runners.py", line 103, in initialize
    self.load_checkpoint()
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/model_runners.py", line 181, in load_checkpoint
    self.ckpt  = torch.load(
                 ^^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/clustersw/Debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I have already redownloaded the models again but to no avail. I checked the path does exist. Can I have the checksums of the files or am I missing something?

**Comment by roccomoretti** [comment]
> `Reading checkpoint from /nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/../../models/Base_ckpt.pt

Was the path you checked that existed `/nfs/scistore07/clustersw/debian/bookworm/RFdiffusion/20240307/lib/python3.11/site-packages/rfdiffusion/inference/../../models/Base_ckpt.pt` ? -- I'll note that's a slightly odd location for it (being in `python3.11/site-packages/models/`), as typically the models are placed in the downloaded RFdiffusion directory, rather than the python site-packages directory.

I'm not sure why it's looking for the models there, but you should be able to use either `inference.model_directory_path` (providing the name of the models/ direcotry) or `inference.ckpt_override_path` (providing the `models/Base_ckpt.pt` filename) to explicitly specify the path to search.
