### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by AIM132** [RosettaCommons/RFdiffusion#238]
I encountered the following error while executing the task. Does anyone know how to resolve it? Thank you.

./scripts/run_inference.py scaffoldguided.target_path=../IL10/IL10RA.pdb inference.output_prefix=IL10_outputs/design_ppi_scaffolded scaffoldguided.scaffoldguided=True 'ppi.hotspot_res=[S44,S76,S96,S101,S190,S191]' scaffoldguided.target_pdb=True scaffoldguided.scaffold_dir=./ppi_scaffolds/ inference.num_designs=5 denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0

Error executing job with overrides: ['scaffoldguided.target_path=./IL10/IL10RA.pdb', 'inference.output_prefix=IL10_outputs/design_ppi_scaffolded', 'scaffoldguided.scaffoldguided=True', 'ppi.hotspot_res=[S44,S76,S96,S101]', 'scaffoldguided.target_pdb=True', 'scaffoldguided.scaffold_dir=./ppi_scaffolds/', 'inference.num_designs=5', 'denoiser.noise_scale_ca=0', 'denoiser.noise_scale_frame=0']
Traceback (most recent call last):
  File "/home/L/RFdiffusion/./scripts/run_inference.py", line 84, in main
    x_init, seq_init = sampler.sample_init()
  File "/home/L/RFdiffusion/rfdiffusion/inference/model_runners.py", line 776, in sample_init
    self.L, self.ss, self.adj = self.blockadjacency.get_scaffold()
  File "/home/L/RFdiffusion/rfdiffusion/inference/utils.py", line 891, in get_scaffold
    item = random.choice(self.scaffold_list)
  File "/home/L/miniconda3/envs/SE3nv/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by AIM132** [comment]
I know how to solve it now. It was a path specification error in the code, and I hope it can be a reference for future generations

**Comment by 1326093445a** [comment]
Hello, could you share how you solve this problem, I'm also encountering the same problem. Thank you for your help!
