### ISSUE TITLE
ImportError: cannot import name 'SE3Transformer'

### ISSUE THREAD

**Issue by partrita** [RosettaCommons/RFdiffusion#260]
```bash
**Traceback (most recent call last):
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/./scripts/run_inference.py", line 27, in <module>
    from rfdiffusion.inference import utils as iu
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/inference/utils.py", line 12, in <module>
    from rfdiffusion.inference import model_runners
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/inference/model_runners.py", line 4, in <module>
    from rfdiffusion.RoseTTAFoldModel import RoseTTAFoldModule
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/RoseTTAFoldModel.py", line 3, in <module>
    from rfdiffusion.Embeddings import MSA_emb, Extra_emb, Templ_emb, Recycling
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/Embeddings.py", line 7, in <module>
    from rfdiffusion.Track_module import PairStr2Pair
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/Track_module.py", line 4, in <module>
    from rfdiffusion.SE3_network import SE3TransformerWrapper
  File "/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion/rfdiffusion/SE3_network.py", line 8, in <module>
    from se3_transformer.model import SE3Transformer
ImportError: cannot import name 'SE3Transformer' from 'se3_transformer.model' (/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9/site-packages/se3_transformer-1.0.0-py3.9.egg/se3_transformer/model/__init__.py)
```

I got this error massage, please help!

```bash
RFdiffusion on  main [?⇡] via 🐍 v3.9.19 via 🅒 SE3nv-cuda117 took 58s 
❯ python -m pip show se3_transformer
Name: se3-transformer
Version: 1.0.0
Summary: PyTorch + DGL implementation of SE(3)-Transformers
Home-page: 
Author: Alexandre Milesi
Author-email: alexandrem@nvidia.com
License: 
Location: /home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9/site-packages/se3_transformer-1.0.0-py3.9.egg
Requires: 
Required-by: rfdiffusion

RFdiffusion on  main [?⇡] via 🐍 v3.9.19 via 🅒 SE3nv-cuda117 
❯ python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python39.zip', '/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9', '/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9/lib-dynload', '/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9/site-packages', '/home/fkt/mambaforge/envs/SE3nv-cuda117/lib/python3.9/site-packages/se3_transformer-1.0.0-py3.9.egg', '/mnt/c4a1c56d-0589-48cd-9717-f6c33a86fa3b/RFdiffusion']
```

It just a huge pain in my ass.

**Comment by roccomoretti** [comment]
For RFdiffusion, the se3_transformer package should be installed from the version which is included in the repository. The steps in the [Conda Install SE3-Transformer](https://github.com/RosettaCommons/RFdiffusion?tab=readme-ov-file#conda-install-se3-transformer) section of the README should describe how to set up a conda environment and install the version of se3_transformer that RFdiffusion expects.

**Comment by partrita** [comment]
> For RFdiffusion, the se3_transformer package should be installed from the version which is included in this repository. The steps in the [Conda Install SE3-Transformer](https://github.com/RosettaCommons/RFdiffusion?tab=readme-ov-file#conda-install-se3-transformer) section of the README should describe how to set up a conda environment and install the version of se3_transformer that RFdiffusion expects.

I followed that instructions but I guess something wrong in my PC. Therefore, I just delete OS and reinstall everything.
