### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by zarbuk** [RosettaCommons/RFdiffusion#283]
Hello , 
I keep getting this error while running the script for generating the backbone while using motif scaffolding with target. Can someone let me know what is the issue?

my runs are getting terminated prematurely for RF diffusion and I end up getting this error times and again:

Traceback (most recent call last):
  File "/home/zbukhari/RFdiffusion/scripts/run_inference.py", line 94, in main
    px0, x_t, seq_t, plddt = sampler.sample_step(
  File "/home/zbukhari/RFdiffusion/rfdiffusion/inference/model_runners.py", line 695, in sample_step
    x_t_1, px0 = self.denoiser.get_next_pose(
  File "/home/zbukhari/RFdiffusion/rfdiffusion/inference/utils.py", line 471, in get_next_pose
    frames_next = get_next_frames(
  File "/home/zbukhari/RFdiffusion/rfdiffusion/inference/utils.py", line 67, in get_next_frames
    ] = diffuser.so3_diffuser.reverse_sample_vectorized(
  File "/home/zbukhari/RFdiffusion/rfdiffusion/diffusion.py", line 500, in reverse_sample_vectorized
    scipy_R.from_matrix(R_0t.cpu().numpy()).as_rotvec()
  File "_rotation.pyx", line 759, in scipy.spatial.transform._rotation.Rotation.from_matrix
  File "_rotation.pyx", line 19, in scipy.spatial.transform._rotation._empty2

Regards,
Zara

**Comment by zarbuk** [comment]
@RosettaCommons/industrialcontributors can someone help me with this issue please?
@lyskov
