### ISSUE TITLE
SVD error

### ISSUE THREAD

**Issue by soumadwip** [RosettaCommons/RFdiffusion#284]
Hi, I am trying to run a basic script design_ppi.sh  as it is after fresh installing RFdiffusion. It is throwing the following error: "numpy.linalg.LinAlgError: SVD did not converge". Could you please help me troubleshooting this?

Thank you,
Soumadwip

**Comment by Forever8341** [comment]
I got the same error with pytorch 2.9. When I use torch 1.9, everything is find. However, torch1.9 doesnt support rtx pro 6000. I think this error caused by the different version of torch. You can try to use torch1.9.

**Comment by rclune** [comment]
My environment uses pytorch 2.5.1 (py3.9_cuda11.8_cudnn9.1.0_0) and does not run into this issue. Can you provide more details about your system and environment? 

If you have a system that doesn't support CUDA versions below 12 you may need to change several of the installed libraries to have it work. A previous issue ([https://github.com/RosettaCommons/RFdiffusion/issues/422](https://github.com/RosettaCommons/RFdiffusion/issues/422)) produced an updated installation guide for systems requiring CUDA 12.x and python 3.11 that might be useful.

**Comment by Forever8341** [comment]
My system is Ubuntu 24.04 LTS. I am using CUDA 12, and it works fine with 4090 and V100. However, the same setup doesn’t work for GPUs with the Blackwell architecture (only works for pytorch >2.7). The current GPU I’m using is the RTX PRO 6000. The error I’m getting is: "numpy.linalg.LinAlgError: SVD did not converge". I assume the error is caused by the different verison of torch. 
Below is part of my environment setup. 



cuda-cudart                 12.4.127         0                     nvidia
cuda-cupti                  12.4.127         0                     nvidia
cuda-libraries              12.4.1           0                     nvidia
cuda-nvrtc                  12.4.127         0                     nvidia
cuda-nvtx                   12.4.127         0                     nvidia
cuda-opencl                 12.4.127         0                     nvidia
cuda-runtime                12.4.1           0                     nvidia
cuda-version                11.7             h67201e3_3            conda-forge
cudatoolkit                 11.7.0           hd8887f6_10           nvidia
dgl-cuda11.1                0.9.1post1       py39_0                dglteam
libcublas                   12.4.5.8         0                     nvidia
libcufft                    11.2.1.3         0                     nvidia
libcufile                   1.9.1.3          0                     nvidia
libcurand                   10.3.5.147       0                     nvidia
libcusolver                 11.6.1.9         0                     nvidia
libcusparse                 12.3.1.170       0                     nvidia
ncurses                     6.5              h2d0b736_3            conda-forge
nvidia-cublas-cu12          12.6.4.1         pypi_0                pypi
nvidia-cuda-cupti-cu12      12.6.80          pypi_0                pypi
nvidia-cuda-nvrtc-cu12      12.6.77          pypi_0                pypi
nvidia-cuda-runtime-cu12    12.6.77          pypi_0                pypi
nvidia-cudnn-cu12           9.5.1.17         pypi_0                pypi
nvidia-cufft-cu12           11.3.0.4         pypi_0                pypi
nvidia-cufile-cu12          1.11.1.6         pypi_0                pypi
nvidia-curand-cu12          10.3.7.77        pypi_0                pypi
nvidia-cusolver-cu12        11.7.1.2         pypi_0                pypi
nvidia-cusparse-cu12        12.5.4.2         pypi_0                pypi
nvidia-cusparselt-cu12      0.6.3            pypi_0                pypi
nvidia-nccl-cu12            2.26.2           pypi_0                pypi
nvidia-nvjitlink-cu12       12.6.85          pypi_0                pypi
nvidia-nvtx-cu12            12.6.77          pypi_0                pypi
pytorch-cuda                12.4             hc786d27_7            pytorch
torch                       2.7.1+cu126      pypi_0                pypi
torchaudio                  2.7.1+cu126      pypi_0                pypi
torchvision                 0.22.1+cu126     pypi_0                pypi

**Comment by rclune** [comment]
I would make sure that all of the dependencies that depend on a specific CUDA or Python version match. For example, it looks like your pytorch-cuda is relying on cuda 12.4, but torch is for cuda 12.6. I didn't see any obvious python versioning errors in your list, but note that DGL is expecting python 3.9.

**Comment by Forever8341** [comment]
Python version is 3.9.23. Torch2.7 gave me the error message, and I updated it to 2.8. It gave me the same error message. When I run RFdiffusion/examples/design_ppi.sh, here is the error mesage I got. 

Error executing job with overrides: ['inference.output_prefix=example_outputs/design_ppi', 'inference.input_pdb=input_pdbs/insulin_target.pdb', 'contigmap.contigs=[A1-150/0 70-100]', 'ppi.hotspot_res=[A59,A83,A91]', 'inference.num_designs=10', 'denoiser.noise_scale_ca=0', 'denoiser.noise_scale_frame=0']
Traceback (most recent call last):
  File "/home/jedi/App/RFdiffusion/examples/../scripts/run_inference.py", line 94, in main
    px0, x_t, seq_t, plddt = sampler.sample_step(
  File "/home/jedi/App/RFdiffusion/rfdiffusion/inference/model_runners.py", line 881, in sample_step
    x_t_1, px0 = self.denoiser.get_next_pose(
  File "/home/jedi/App/RFdiffusion/rfdiffusion/inference/utils.py", line 448, in get_next_pose
    px0 = self.align_to_xt_motif(px0, xt, diffusion_mask)
  File "/home/jedi/App/RFdiffusion/rfdiffusion/inference/utils.py", line 335, in align_to_xt_motif
    U, S, Vt = np.linalg.svd(C)
  File "<__array_function__ internals>", line 180, in svd
  File "/home/jedi/miniconda3/envs/SE3nv/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1648, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/jedi/miniconda3/envs/SE3nv/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
**numpy.linalg.LinAlgError: SVD did not converge**

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.


BUT, the conda environment is totally fine with the /RFdiffusion/examples/design_macrocyclic_monomer.sh script. 


Here is my conda dependencies. 
The 
# Name                      Version          Build                 Channel
_libgcc_mutex               0.1              conda_forge           conda-forge
_openmp_mutex               4.5              2_gnu                 conda-forge
antlr-python-runtime        4.9.3            pyhd8ed1ab_1          conda-forge
brotli-python               1.1.0            py39hf88036b_3        conda-forge
bzip2                       1.0.8            hda65f42_8            conda-forge
ca-certificates             2025.11.12       hbd8a1cb_0            conda-forge
certifi                     2025.8.3         pyhd8ed1ab_0          conda-forge
cffi                        1.17.1           py39h15c3d72_0        conda-forge
charset-normalizer          3.4.3            pyhd8ed1ab_0          conda-forge
click                       8.1.8            pypi_0                pypi
colorama                    0.4.6            pyhd8ed1ab_1          conda-forge
configparser                7.2.0            pypi_0                pypi
cpython                     3.9.23           py39hd8ed1ab_0        conda-forge
cuda-cudart                 12.4.127         0                     nvidia
cuda-cupti                  12.4.127         0                     nvidia
cuda-libraries              12.4.1           0                     nvidia
cuda-nvrtc                  12.4.127         0                     nvidia
cuda-nvtx                   12.4.127         0                     nvidia
cuda-opencl                 12.4.127         0                     nvidia
cuda-runtime                12.4.1           0                     nvidia
cuda-version                11.7             h67201e3_3            conda-forge
cudatoolkit                 11.7.0           hd8887f6_10           nvidia
decorator                   5.1.0            pypi_0                pypi
dgl-cuda11.1                0.9.1post1       py39_0                dglteam
dllogger                    1.1.0            pypi_0                pypi
docker-pycreds              0.4.0            pypi_0                pypi
e3nn                        0.3.3            pypi_0                pypi
filelock                    3.19.1           pypi_0                pypi
fsspec                      2025.10.0        pypi_0                pypi
gitdb                       4.0.12           pypi_0                pypi
gitpython                   3.1.45           pypi_0                pypi
gmp                         6.3.0            hac33072_2            conda-forge
gmpy2                       2.2.1            py39h7196dd7_0        conda-forge
h2                          4.2.0            pyhd8ed1ab_0          conda-forge
hpack                       4.1.0            pyhd8ed1ab_0          conda-forge
hydra-core                  1.3.2            pyhd8ed1ab_1          conda-forge
hyperframe                  6.1.0            pyhd8ed1ab_0          conda-forge
idna                        3.10             pyhd8ed1ab_1          conda-forge
importlib-metadata          8.7.0            pypi_0                pypi
intel-openmp                2025.0.0         h06a4308_1171
jinja2                      3.1.6            pypi_0                pypi
ld_impl_linux-64            2.45             default_hbd61a6d_104  conda-forge
libblas                     3.8.0            16_mkl                conda-forge
libcblas                    3.8.0            16_mkl                conda-forge
libcublas                   12.4.5.8         0                     nvidia
libcufft                    11.2.1.3         0                     nvidia
libcufile                   1.9.1.3          0                     nvidia
libcurand                   10.3.5.147       0                     nvidia
libcusolver                 11.6.1.9         0                     nvidia
libcusparse                 12.3.1.170       0                     nvidia
libexpat                    2.7.3            hecca717_0            conda-forge
libffi                      3.5.2            h9ec8514_0            conda-forge
libgcc                      15.2.0           he0feb66_14           conda-forge
libgcc-ng                   15.2.0           h69a702a_14           conda-forge
libgfortran-ng              7.5.0            h14aa051_20           conda-forge
libgfortran4                7.5.0            h14aa051_20           conda-forge
libgfortran5                15.2.0           h68bc16d_14           conda-forge
libgomp                     15.2.0           he0feb66_14           conda-forge
liblapack                   3.8.0            16_mkl                conda-forge
liblzma                     5.8.1            hb9d3cd8_2            conda-forge
libnpp                      12.2.5.30        0                     nvidia
libnsl                      2.0.1            hb9d3cd8_1            conda-forge
libnvfatbin                 12.4.127         0                     nvidia
libnvjitlink                12.4.127         0                     nvidia
libnvjpeg                   12.3.1.117       0                     nvidia
libsqlite                   3.51.1           h0c1763c_0            conda-forge
libstdcxx                   15.2.0           h934c35e_14           conda-forge
libstdcxx-ng                15.2.0           hdf11a46_14           conda-forge
libuuid                     2.41.2           he9a06e4_0            conda-forge
libxcrypt                   4.4.36           hd590300_1            conda-forge
libzlib                     1.3.1            hb9d3cd8_2            conda-forge
markupsafe                  3.0.3            pypi_0                pypi
mkl                         2020.2           256
mpc                         1.3.1            h24ddda3_1            conda-forge
mpfr                        4.2.1            h90cbb55_3            conda-forge
mpmath                      1.3.0            pyhd8ed1ab_1          conda-forge
ncurses                     6.5              h2d0b736_3            conda-forge
networkx                    3.2              pyhd8ed1ab_0          conda-forge
numpy                       1.22.4           py39hc58783e_0        conda-forge
nvidia-cublas-cu12          12.8.4.1         pypi_0                pypi
nvidia-cuda-cupti-cu12      12.8.90          pypi_0                pypi
nvidia-cuda-nvrtc-cu12      12.8.93          pypi_0                pypi
nvidia-cuda-runtime-cu12    12.8.90          pypi_0                pypi
nvidia-cudnn-cu12           9.10.2.21        pypi_0                pypi
nvidia-cufft-cu12           11.3.3.83        pypi_0                pypi
nvidia-cufile-cu12          1.13.1.3         pypi_0                pypi
nvidia-curand-cu12          10.3.9.90        pypi_0                pypi
nvidia-cusolver-cu12        11.7.3.90        pypi_0                pypi
nvidia-cusparse-cu12        12.5.8.93        pypi_0                pypi
nvidia-cusparselt-cu12      0.7.1            pypi_0                pypi
nvidia-nccl-cu12            2.27.3           pypi_0                pypi
nvidia-nvjitlink-cu12       12.8.93          pypi_0                pypi
nvidia-nvtx-cu12            12.8.90          pypi_0                pypi
ocl-icd                     2.3.3            hb9d3cd8_0            conda-forge
omegaconf                   2.3.0            pyhd8ed1ab_0          conda-forge
opencl-headers              2025.06.13       h5888daf_0            conda-forge
openssl                     3.6.0            h26f9b46_0            conda-forge
opt-einsum                  3.4.0            pypi_0                pypi
opt-einsum-fx               0.1.4            pypi_0                pypi
packaging                   25.0             pyh29332c3_1          conda-forge
pathtools                   0.1.2            pypi_0                pypi
pillow                      11.3.0           pypi_0                pypi
pip                         25.2             pyh8b19718_0          conda-forge
promise                     2.3              pypi_0                pypi
protobuf                    6.33.1           pypi_0                pypi
psutil                      7.0.0            py39h8cd3c5a_0        conda-forge
pycparser                   2.22             pyh29332c3_1          conda-forge
pynvml                      11.0.0           pypi_0                pypi
pyrsistent                  0.20.0           py39h8cd3c5a_1        conda-forge
pysocks                     1.7.1            pyha55dd90_7          conda-forge
python                      3.9.23           hc30ae73_0_cpython    conda-forge
python-dateutil             2.9.0.post0      pypi_0                pypi
python_abi                  3.9              8_cp39                conda-forge
pytorch-cuda                12.4             hc786d27_7            pytorch
pyyaml                      6.0.2            py39h9399b63_2        conda-forge
readline                    8.2              h8c095d6_2            conda-forge
requests                    2.32.5           pyhd8ed1ab_0          conda-forge
rfdiffusion                 1.1.0            pypi_0                pypi
scipy                       1.8.1            py39he49c0e8_0        conda-forge
se3-transformer             1.0.0            pypi_0                pypi
sentry-sdk                  2.46.0           pypi_0                pypi
setuptools                  80.9.0           pyhff2d567_0          conda-forge
shortuuid                   1.0.13           pypi_0                pypi
six                         1.17.0           pypi_0                pypi
smmap                       5.0.2            pypi_0                pypi
subprocess32                3.5.4            pypi_0                pypi
sympy                       1.14.0           pypi_0                pypi
tk                          8.6.13           noxft_ha0e22de_103    conda-forge
torch                       2.8.0            pypi_0                pypi
torchvision                 0.23.0           pypi_0                pypi
tqdm                        4.67.1           pyhd8ed1ab_1          conda-forge
triton                      3.4.0            pypi_0                pypi
typing_extensions           4.14.1           pyhe01879c_0          conda-forge
tzdata                      2025b            h78e105d_0            conda-forge
urllib3                     2.5.0            pyhd8ed1ab_0          conda-forge
wandb                       0.12.0           pypi_0                pypi
wheel                       0.45.1           pyhd8ed1ab_1          conda-forge
yaml                        0.2.5            h280c20c_3            conda-forge
zipp                        3.23.0           pypi_0                pypi
zstandard                   0.23.0           py39hd399759_3        conda-forge
zstd                        1.5.7            h3691f8a_4            conda-forge
