### ISSUE TITLE
why there is no example for design binder for protein complex

### ISSUE THREAD

**Issue by MaoSihong** [RosettaCommons/RFdiffusion#37]
I got error with paras like this, i wonder if it is a incompatible problem that i try to design binder for more than one molecule? ['contigmap.contigs=[C/0 F/0 100-120]', 'ppi.hotspot_res=[C80,C82,C86,C87,C90,C92,C93,E128,C138,C185,C187]', 'denoiser.noise_scale_ca=0', 'denoiser.noise_scale_frame=0'
Traceback (most recent call last):
  File "/Share/app/RFdiffusion/scripts/run_inference.py", line 194, in <module>
    main()
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/Share/app/miniconda3.9/envs/SE3nv/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Share/app/RFdiffusion/scripts/run_inference.py", line 84, in main
    x_init, seq_init = sampler.sample_init()
  File "/Share/app/RFdiffusion/rfdiffusion/inference/model_runners.py", line 278, in sample_init
    self.contig_map = self.construct_contig(self.target_feats)
  File "/Share/app/RFdiffusion/rfdiffusion/inference/model_runners.py", line 240, in construct_contig
    return ContigMap(target_feats, **self.contig_conf)
  File "/Share/app/RFdiffusion/rfdiffusion/contigs.py", line 78, in __init__
    ) = self.expand_sampled_mask()
  File "/Share/app/RFdiffusion/rfdiffusion/contigs.py", line 225, in expand_sampled_mask
    int(subcon.split("-")[0][1:]), int(subcon.split("-")[1]) + 1
ValueError: invalid literal for int() with base 10: ''

**Comment by KoubaPetr** [comment]
Maybe a typo? You provide chains C and F, but in hotspots (E128), you want to bind to E.

**Comment by MaoSihong** [comment]
i follow the trace back, noticing that i should always assign the residue idx for exist chain to avoid invalid int(subcon.split("-")[0][1:]), further i'd have to modify the code here:
![image](https://user-images.githubusercontent.com/50494689/235066862-5a8a2d67-3a91-442f-ab94-507791a09e2d.png)
![image](https://user-images.githubusercontent.com/50494689/235066948-53afe58d-a7af-4083-88e7-e9cb6f136d33.png)
in model_runners.py to make consistent tensor dtype. hope to help with better code and friendly usage! good luck!
