### ISSUE TITLE
Help: RFdiffusion EOFError: Ran out of input

### ISSUE THREAD

**Issue by songhe2009** [RosettaCommons/RFdiffusion#67]
Dear all, please help me with this error. Thank you very much. 

./scripts/run_inference.py 'contigmap.contigs=[150-150]' inference.output_prefix=test_outputs/test inference.num_designs=10

[2023-06-04 19:49:19,789][__main__][INFO] - Found GPU with device_name NVIDIA GeForce RTX 3090. Will run RFdiffusion on NVIDIA GeForce RTX 3090
Reading models from /home/hesong/local/RFdiffusion/rfdiffusion/inference/../../models
[2023-06-04 19:49:19,790][rfdiffusion.inference.model_runners][INFO] - Reading checkpoint from /home/hesong/local/RFdiffusion/rfdiffusion/inference/../../models/Base_ckpt.pt
This is inf_conf.ckpt_path
/home/hesong/local/RFdiffusion/rfdiffusion/inference/../../models/Base_ckpt.pt
Assembling -model, -diffuser and -preprocess configs from checkpoint
USING MODEL CONFIG: self._conf[model][n_extra_block] = 4
USING MODEL CONFIG: self._conf[model][n_main_block] = 32
USING MODEL CONFIG: self._conf[model][n_ref_block] = 4
USING MODEL CONFIG: self._conf[model][d_msa] = 256
USING MODEL CONFIG: self._conf[model][d_msa_full] = 64
USING MODEL CONFIG: self._conf[model][d_pair] = 128
USING MODEL CONFIG: self._conf[model][d_templ] = 64
USING MODEL CONFIG: self._conf[model][n_head_msa] = 8
USING MODEL CONFIG: self._conf[model][n_head_pair] = 4
USING MODEL CONFIG: self._conf[model][n_head_templ] = 4
USING MODEL CONFIG: self._conf[model][d_hidden] = 32
USING MODEL CONFIG: self._conf[model][d_hidden_templ] = 32
USING MODEL CONFIG: self._conf[model][p_drop] = 0.15
USING MODEL CONFIG: self._conf[model][SE3_param_full] = {'num_layers': 1, 'num_channels': 32, 'num_degrees': 2, 'n_heads': 4, 'div': 4, 'l0_in_features': 8, 'l0_out_features': 8, 'l1_in_features': 3, 'l1_out_features': 2, 'num_edge_features': 32}
USING MODEL CONFIG: self._conf[model][SE3_param_topk] = {'num_layers': 1, 'num_channels': 32, 'num_degrees': 2, 'n_heads': 4, 'div': 4, 'l0_in_features': 64, 'l0_out_features': 64, 'l1_in_features': 3, 'l1_out_features': 2, 'num_edge_features': 64}
USING MODEL CONFIG: self._conf[model][freeze_track_motif] = False
USING MODEL CONFIG: self._conf[model][use_motif_timestep] = True
USING MODEL CONFIG: self._conf[diffuser][T] = 50
USING MODEL CONFIG: self._conf[diffuser][b_0] = 0.01
USING MODEL CONFIG: self._conf[diffuser][b_T] = 0.07
USING MODEL CONFIG: self._conf[diffuser][schedule_type] = linear
USING MODEL CONFIG: self._conf[diffuser][so3_type] = igso3
USING MODEL CONFIG: self._conf[diffuser][crd_scale] = 0.25
USING MODEL CONFIG: self._conf[diffuser][so3_schedule_type] = linear
USING MODEL CONFIG: self._conf[diffuser][min_b] = 1.5
USING MODEL CONFIG: self._conf[diffuser][max_b] = 2.5
USING MODEL CONFIG: self._conf[diffuser][min_sigma] = 0.02
USING MODEL CONFIG: self._conf[diffuser][max_sigma] = 1.5
USING MODEL CONFIG: self._conf[preprocess][sidechain_input] = False
USING MODEL CONFIG: self._conf[preprocess][motif_sidechain_input] = True
USING MODEL CONFIG: self._conf[preprocess][d_t1d] = 22
USING MODEL CONFIG: self._conf[preprocess][d_t2d] = 44
USING MODEL CONFIG: self._conf[preprocess][prob_self_cond] = 0.5
USING MODEL CONFIG: self._conf[preprocess][str_self_cond] = True
USING MODEL CONFIG: self._conf[preprocess][predict_previous] = False
[2023-06-04 19:49:22,270][rfdiffusion.inference.model_runners][INFO] - Loading checkpoint.
[2023-06-04 19:49:24,666][rfdiffusion.diffusion][INFO] - Using cached IGSO3.
Error executing job with overrides: ['contigmap.contigs=[150-150]', 'inference.output_prefix=test_outputs/test', 'inference.num_designs=10']
Traceback (most recent call last):
  File "/home/hesong/local/RFdiffusion/./scripts/run_inference.py", line 54, in main
    sampler = iu.sampler_selector(conf)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/inference/utils.py", line 511, in sampler_selector
    sampler = model_runners.SelfConditioning(conf)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/inference/model_runners.py", line 37, in __init__
    self.initialize(conf)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/inference/model_runners.py", line 130, in initialize
    self.diffuser = Diffuser(**self._conf.diffuser, cache_dir=schedule_directory)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/diffusion.py", line 582, in __init__
    self.so3_diffuser = IGSO3(
  File "/home/hesong/local/RFdiffusion/rfdiffusion/diffusion.py", line 198, in __init__
    self.igso3_vals = self._calc_igso3_vals(L=L)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/diffusion.py", line 233, in _calc_igso3_vals
    igso3_vals = read_pkl(cache_fname)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/diffusion.py", line 144, in read_pkl
    raise (e)
  File "/home/hesong/local/RFdiffusion/rfdiffusion/diffusion.py", line 140, in read_pkl
    return pickle.load(handle)
EOFError: Ran out of input

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by protbiochem** [comment]
Did you ever solve this issue? Running into the same thing here
