### ISSUE TITLE
OSError: [Errno 30] Read-only file system: 'outputs'

### ISSUE THREAD

**Issue by maxh190** [RosettaCommons/RFdiffusion#79]
After having built RFdiffusion's docker container and pulled it to our HPC, I have run the following test by using singularity:
```
singularity run --env TF_FORCE_UNIFIED_MEMORY=1,XLA_PYTHON_CLIENT_MEM_FRACTION=4.0,OPENMM_CPU_THREADS=10,HYDRA_FULL_ERROR=1 \
        -B $HOME/outputs:$HOME/outputs \
        --pwd /app/RFdiffusion \
        --nv $HOME/rfdiffusion/rfdiffusion_v1.1.0.sif \
        inference.output_prefix=$HOME/outputs/motifscaffolding \
        inference.model_directory_path=$HOME/models \
        inference.input_pdb=$HOME/inputs/5TPN.pdb \
        inference.num_designs=3 \
        'contigmap.contigs=[10-40/A163-181/10-40]'

```
However, I got errors as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/2023-06-24/15-54-50'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/2023-06-24'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/RFdiffusion/scripts/run_inference.py", line 194, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/usr/local/lib/python3.9/dist-packages/hydra/core/utils.py", line 146, in run_job
    Path(str(output_dir)).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.9/pathlib.py", line 1317, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.9/pathlib.py", line 1317, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: 'outputs'

```
Can you please let me know what I did incorrectly?
Thanks a lot in advance.

**Comment by roccomoretti** [comment]
RFDiffusion uses Hydra (https://hydra.cc) to handle setup and configuration. By default, Hydra [sets up an output/logging directory](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/) where it stores run information. You're failing in trying to set up that directory (probably because the default location under the working directory isn't writable.)

You should be able to change where this directory is written to by adding `hydra.output_subdir=<dirname>` to the command line. Alternatively, you can add `hydra.output_subdir=null` to turn the feature off.
