### ISSUE TITLE
Help with error: no such file or directory /models/Base_ckpt.pt

### ISSUE THREAD

**Issue by ttessie2** [RosettaCommons/RFdiffusion#80]
I've just set this up in WSL2 and had no issues during setup. I just copied the unconditional design example to quickly test if it works but I'm getting the error below. I'm not sure how to interpret this error so any help would be great!

~/RFdiffusion$ scripts/run_inference.py inference.output_prefix=example_outputs/design_unconditional 'contigmap.contigs=[100-200]' inference.num_designs=10
[2023-06-26 22:44:09,438][__main__][INFO] - Found GPU with device_name NVIDIA GeForce RTX 3060. Will run RFdiffusion on NVIDIA GeForce RTX 3060
Reading models from /home/usr/RFdiffusion/rfdiffusion/inference/../../models
[2023-06-26 22:44:09,439][rfdiffusion.inference.model_runners][INFO] - Reading checkpoint from /home/usr/RFdiffusion/rfdiffusion/inference/../../models/Base_ckpt.pt
This is inf_conf.ckpt_path
/home/usr/RFdiffusion/rfdiffusion/inference/../../models/Base_ckpt.pt
Error executing job with overrides: ['inference.output_prefix=example_outputs/design_unconditional', 'contigmap.contigs=[100-200]', 'inference.num_designs=10']
Traceback (most recent call last):
  File "/home/usr/RFdiffusion/scripts/run_inference.py", line 54, in main
    sampler = iu.sampler_selector(conf)
  File "/home/usr/RFdiffusion/rfdiffusion/inference/utils.py", line 511, in sampler_selector
    sampler = model_runners.SelfConditioning(conf)
  File "/home/usr/RFdiffusion/rfdiffusion/inference/model_runners.py", line 37, in __init__
    self.initialize(conf)
  File "/home/usr/RFdiffusion/rfdiffusion/inference/model_runners.py", line 103, in initialize
    self.load_checkpoint()
  File "/home/usr/RFdiffusion/rfdiffusion/inference/model_runners.py", line 181, in load_checkpoint
    self.ckpt  = torch.load(
  File "/home/usr/anaconda3/envs/SE3nv/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/usr/anaconda3/envs/SE3nv/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/usr/anaconda3/envs/SE3nv/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/usr/RFdiffusion/rfdiffusion/inference/../../models/Base_ckpt.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by roccomoretti** [comment]
Did you complete the model download step? (The `wget` commands in https://github.com/RosettaCommons/RFdiffusion#getting-started--installation) -- Note that this needs to be done within the RFDiffusion directory created by the prior `git clone` command, so you should have a `/home/usr/RFdiffusion/models` directory, and not a `/home/usr/models/` directory.

**Comment by ttessie2** [comment]
Yes I completed it. I followed the install instructions verbatim. I think I messed up the directory part. The models are in usr. I suspected they shouldn't be there but I didn't know where to put them.
Unfortunately, this is all set up on my personal computer at home so will mess with this tonight. Will moving the models folder into the RFdiffusion directory suffice? Or should I redo the install?

**Comment by ttessie2** [comment]
Thank you! I'll leave this open for now, until I can verify this works.

**Comment by ttessie2** [comment]
Works great, no issues!
